src/StackWarden.UI/Models/Monitor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using StackWarden.Monitoring;

namespace StackWarden.UI.Models
{
    public class Monitor
    {
        public string Name { get; set; }
        public string TargetName { get; set; }
        public string State { get; set; }
        public string Message { get; set; }
        public string Icon { get; set; }
        public List<string> Tags { get; set; }
        public Dictionary<string, object> Details { get; set; }
        public DateTime StaleAfter { get; set; }
        public List<Tool> Tools { get; set; }

        public static implicit operator Monitor(Result result)
        {
            var lenientTimeToLive = result.TimeToLive + Constants.Monitor.TimeToLiveLeniency;
            var projectedResultLife = result.SentOn.AddMilliseconds(lenientTimeToLive.TotalMilliseconds);

            var model = new Monitor
            {
                Name = result.Source.Name,
                TargetName = result.Target.Name,
                State = result.Target.State.ToString(),
                Message = result.Message,
                StaleAfter = projectedResultLife,
                Icon = GetIcon(result.Source.Type),
                Tags = result.Tags.ToList()
            };

            if (result.Metadata != null)
                model.Details = new Dictionary<string, object>(result.Metadata);
            
            return model;
        }

        private static string GetIcon(Type monitorType)
        {
            var namespaceName = monitorType.Namespace.Split('.').LastOrDefault();
            var foundIcon = Constants.Icons.Map.ContainsKey(namespaceName)
                                ? Constants.Icons.Map[namespaceName]
                                : null;

            return foundIcon;
        }
    }
}

src/StackWarden.UI/Models/NavigationCategories.cs
using System.Collections.Generic;

namespace StackWarden.UI.Models
{
    public class NavigationCategories
    {
        public List<string> Categories { get; } = new List<string>();
    }
}

src/StackWarden.UI/Models/Tool.cs
namespace StackWarden.UI.Models
{
    public class Tool
    {
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

src/StackWarden.UI/Controllers/Api/MonitorController.cs
using System.Web.Http;
using Microsoft.AspNet.SignalR;
using log4net;
using StackWarden.Monitoring;
using StackWarden.Core.Extensions;
using StackWarden.Core.Persistence;
using StackWarden.UI.Hubs;

namespace StackWarden.UI.Controllers.Api
{
    [AllowAnonymous]
    [RoutePrefix("api/monitor")]
    public class MonitorController : ApiController
    {
        private readonly ILog _log;
        //private readonly IMonitorService _monitorService;

        public MonitorController(ILog log/*, IMonitorService monitorService*/)
        {
            _log = log.ThrowIfNull(nameof(log));
            //_monitorService = monitorService.ThrowIfNull(nameof(monitorService));
        }

        [HttpPost]
        [Route("result/hook")]
        public void ResultHook(Result result)
        {
          //  _monitorService.Save(result);
            NotifyResultAdded(result);
        }

        private void NotifyResultAdded(Result result)
        {
            var resultModel = (Models.Monitor)result;

            GlobalHost.ConnectionManager
                      .GetHubContext<NotificationHub>()
                      .Clients.All.addMonitorResult(resultModel);
        }
    }
}

src/StackWarden.UI/Controllers/Api/ToolController.cs
using System;
using System.Web.Http;

namespace StackWarden.UI.Controllers.Api
{
    public class ToolController : ApiController
    {
        public string Execute(string toolName)
        {
            throw new NotImplementedException();
        }
    }
}

src/StackWarden.UI/Controllers/HomeController.cs
using System;
using System.Web.Mvc;
using System.Linq;
using log4net;
using StackWarden.Core.Extensions;
using StackWarden.Core.Persistence;
using StackWarden.Monitoring;
using StackWarden.Tools;

using Monitor = StackWarden.UI.Models.Monitor;

namespace StackWarden.UI.Controllers
{
    [RoutePrefix("")]
    public class HomeController : Controller
    {
        private readonly ILog _log;
        private readonly IRepository _repository;

        public HomeController(ILog log, IRepository repository)
        {
            _log = log.ThrowIfNull(nameof(log));
            _repository = repository.ThrowIfNull(nameof(repository));
        }

        [Route("")]
        public ActionResult Index()
        {
            return RedirectToAction("Dashboard");
        }

        [Route("Dashboard")]
        public ActionResult Dashboard()
        {
            var results = _repository.Query<Result>()
                                     .GroupBy(x => x.Source != null ? x.Source.Name : null)
                                     .Select(x => x.OrderByDescending(r => r.SentOn).First())
                                     .Select(x => (Monitor)x)
                                     .ToList();

            return View(results);
        }

        [Route("home/tagged")]
        public ActionResult Category(string[] tags)
        {
            var monitorResults = _repository.Query<Result>()
                                            .Where(x => !tags.Except(x.Tags).Any())
                                            .GroupBy(x => x.Source != null ? x.Source.Name : null)
                                            .Select(x => x.OrderByDescending(r => r.SentOn).First())
                                            .ToList();
            var results = monitorResults.Select(m =>
                                        {
                                            var monitor = (Monitor)m;
                                            //monitor.Tools = _repository.Query<ITool>()
                                            //                     .Where(t => t.Category == m.SourceCategory)
                                            //                     .Select(t => new Models.Tool
                                            //                     {
                                            //                        Name = t.Name,
                                            //                        Description = t.Description
                                            //                     }).ToList();

                                            return monitor;
                                        });

            return View(results);
        }
    }
}

src/StackWarden.UI/Controllers/NavigationController.cs
using System.Web.Mvc;
using System.Linq;
using StackWarden.Core.Extensions;
using StackWarden.Tools.Services;
using StackWarden.UI.Models;

namespace StackWarden.UI.Controllers
{
    public class NavigationController : Controller
    {
        public ActionResult Index()
        {
            //var toolSets = _toolSetService.Get();
            //var categories = toolSets.SelectMany(x => x.Categories)
            //                         .Distinct();
            var categories = new string[0];
            var model = new NavigationCategories();

            model.Categories.AddRange(categories);

            return PartialView(model);
        }
    }
}

src/StackWarden.UI/Views/Home/Category.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

src/StackWarden.UI/Views/Home/Dashboard.cshtml
@using StackWarden.Core
@model IEnumerable<StackWarden.UI.Models.Monitor>
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var normal = SeverityState.Normal.ToString();
    var warning = SeverityState.Warning.ToString();
    var error = SeverityState.Error.ToString();
}

<link rel="stylesheet" href="~/Content/styles/dashboard.css" />

@section scripts
{
    <script src="~/Content/scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="signalr/hubs"></script>
    <script src="~/Content/scripts/knockout-3.4.0.js"></script>
    <script src="~/Content/scripts/stackwarden.js"></script>
    <script src="~/Content/scripts/monitorResults.js"></script>
    <script src="~/Content/scripts/notifications.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            stackwarden.notifications.enable();
            stackwarden.monitorResults.initialize({
                normal: '@normal',
                warning: '@warning',
                error: '@error',
                initialData: @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model))
            });
        });
    </script>
}

<div class="page-inner">
    <div class="monitorGroupContainer" data-bind="foreach: groups">
        <div class="monitorGroup"
             data-bind="css: {
                            normal: state() === '@normal',
                            warning: state() === '@warning',
                            error: state() === '@error'
                        }">
            <div class="groupName" data-bind="text: groupKey"></div>
            <i class="smallIcon statusIcon fa" data-bind="css: {
                                            'fa-exclamation-triangle': state() == '@warning',
                                            'fa-exclamation-circle': state() == '@error'
                                         }"></i>
            <div class="groupResults" data-bind="foreach: results,
                                                 css: {
                                                    expandedGroupMonitorResults: selectedResult() != null    
                                                 }">
                <div class="resultContainer" data-bind="click: $parent.select, 
                                                        css: { selectedGroupMonitorResult: $parent.selectedResult() && $data == $parent.selectedResult() }">
                    <div class="statusContainer"
                         data-bind="title: details,
                            click: toggleControlPanel,
                            css: {
                                normal: state() === '@normal',
                                warning: state() === '@warning',
                                error: state() === '@error',
                                stale: isStale
                            }">
                        <i class="smallIcon fa fa-chain-broken" data-bind="visible: isStale"></i>
                        <i class="smallIcon fa " data-bind="css: 'fa-' + icon(), visible: !isStale()"></i>
                    </div>
                </div>
            </div>
            <div class="statusMessage"
                 data-bind="text: message,
                            css: {
                                collapsedVertical: !shouldShowMessage()
                            }"></div>
            <div class="controlPanel" data-bind="with: selectedResult, css: { collapsedVertical: !selectedResult() || !shouldShowControlPanel() }">
                <div class="monitorName" data-bind="text: name"></div>
                <div class="message" data-bind="text: message"></div>
                <div class="subPanel toolsPanel" data-bind="css: { collapsedHorizontal: !shouldShowToolsPanel() }">
                    <div class="toggleContainer" data-bind="click: toggleDetailsPanel, visible: hasDetails">
                        <i class="smallIcon fa fa-list-ul"></i>
                        <i class="smallIcon fa fa-angle-right"></i>
                    </div>
                </div>
                <div class="subPanel detailsPanel" data-bind="css: {collapsedHorizontal: !shouldShowDetailsPanel() }">
                    <div class="toggleContainer" data-bind="click: toggleToolsPanel, visible: hasTools">
                        <i class="smallIcon fa fa-angle-left"></i>
                        <i class="smallIcon fa fa-wrench"></i>
                    </div>
                    <table border="0" cellpadding="0" cellspacing="0" data-bind="foreach: details">
                        <tr>
                            <td class="detailData detailName" data-bind="text: key"></td>
                            <td class="detailData detailValue" data-bind="text: value"></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

src/StackWarden.UI/Views/Navigation/Index.cshtml
@model StackWarden.UI.Models.NavigationCategories

<ul class="nav" id="main-menu">
    <li>
        <div class="user-img-div">
            <img src="http://placehold.it/100x100" class="img-thumbnail" />

            <div class="inner-text">
                @(User?.Identity?.Name ?? "")
            </div>
        </div>

    </li>

    <li>
        <a href="@Url.Action("Dashboard", "Home")"><i class="fa fa-dashboard "></i>Dashboard</a>
    </li>

    @foreach (var currentCategory in Model.Categories)
    {
        <li>
            <a href="@Url.Action(currentCategory, "Home")">
                <i class="fa fa-@Constants.Icons.Map[currentCategory]"></i>@currentCategory
             </a>
        </li>
    }
</ul>

src/StackWarden.UI/Views/Shared/ToolSet.cshtml
@using StackWarden.Core.Extensions
@using StackWarden.UI
@model StackWarden.UI.Models.ToolSet
<div class="panel panel-primary">
    <div class="panel-heading">@Model.Name</div>
    <div class="panel-body">
        <p>@Model.Description</p>
        @foreach (var currentTool in Model.Tools)
        {
            <button class="btn btn-primary" title="@($"{currentTool.Description}")">
                <i class="fa fa-@(Constants.Icons.Map.Get(currentTool.Name, Constants.Icons.Default))"></i>
                @currentTool.Name
            </button>
        }
    </div>
</div>

src/StackWarden.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - @Constants.ApplicationName</title>
    @Styles.Render("~/Content/styles")
    
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

    <style type="text/css">
        .navbar{
            display:none;
        }
    </style>
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index")"><img src="http://placehold.it/300x100" alt="@Constants.OrganizationName" /></a>
            </div>

            <div class="header-right">
                <a href="#" class="btn btn-info" title="New Message"><b>30 </b><i class="fa fa-envelope-o fa-2x"></i></a>
                <a href="#" class="btn btn-primary" title="New Task"><b>40 </b><i class="fa fa-bars fa-2x"></i></a>
            </div>
        </nav>
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                @Html.Action("Index", "Navigation")
            </div>

         </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">
                @RenderBody()
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <div id="footer-sec">
        <footer>
            <p>&copy; @DateTime.Now.Year - @Constants.ApplicationName | Design By : <a href="http://www.binarytheme.com/" target="_blank">BinaryTheme.com</a></p>
        </footer>
    </div>
    <!-- /. FOOTER  -->
    
    @*<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="assets/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="assets/js/bootstrap.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="assets/js/jquery.metisMenu.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="assets/js/custom.js"></script>*@

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    
    @RenderSection("scripts", required: false)
</body>
</html>